"""
DataScout — Visualization Component.

Downloads and displays chart images generated by the Code Interpreter.
Supports both direct image bytes (from Bedrock stream) and S3 URI downloads.
"""

import hashlib
from typing import List

import streamlit as st

try:
    from services.s3_handler import S3Handler
except ImportError:
    from streamlit_app.services.s3_handler import S3Handler


def _dedupe_s3_uris(s3_uris: List[str]) -> List[str]:
    """De-duplicate S3 URIs while preserving order."""
    seen = set()
    deduped = []
    for uri in s3_uris:
        if uri and uri not in seen:
            deduped.append(uri)
            seen.add(uri)
    return deduped


def _dedupe_chart_images(chart_images: list) -> list:
    """De-duplicate chart images by byte content hash."""
    seen_hashes = set()
    deduped = []
    for image in chart_images:
        image_bytes = image.get('bytes', b'')
        if not image_bytes:
            continue
        image_hash = hashlib.sha256(image_bytes).hexdigest()
        if image_hash in seen_hashes:
            continue
        seen_hashes.add(image_hash)
        deduped.append(image)
    return deduped


def render_visualization(s3_uris: List[str] = None,
                         chart_images: list = None,
                         s3_handler: S3Handler = None) -> None:
    """Display chart images from direct bytes or S3 downloads.

    Args:
        s3_uris: List of S3 URIs pointing to chart PNG images (fallback).
        chart_images: List of dicts with 'bytes', 'name', 'type' keys
                      (direct from Code Interpreter stream).
        s3_handler: Optional S3Handler instance; creates one if not provided.
    """
    displayed = 0
    s3_uris = _dedupe_s3_uris(s3_uris or [])
    chart_images = _dedupe_chart_images(chart_images or [])

    # ── Priority 1: Direct chart images from Code Interpreter ──────────
    if chart_images:
        for i, img in enumerate(chart_images):
            image_bytes = img.get('bytes', b'')
            file_name = img.get('name', f'chart_{i + 1}.png')
            if image_bytes:
                st.image(
                    image_bytes,
                    caption=f"Chart {i + 1}",
                    width="stretch"
                )
                st.download_button(
                    label=f"📥 Download Chart {i + 1}",
                    data=image_bytes,
                    file_name=file_name,
                    mime="image/png",
                    key=f"download_chart_direct_{i}"
                )
                displayed += 1

    # ── Priority 2: Download from S3 URIs (fallback) ───────────────────
    if s3_uris and displayed == 0:
        if s3_handler is None:
            s3_handler = S3Handler()

        for i, uri in enumerate(s3_uris):
            try:
                image_bytes = s3_handler.download_artifact(uri)
                st.image(
                    image_bytes,
                    caption=f"Chart {displayed + 1}",
                    width="stretch"
                )
                st.download_button(
                    label=f"📥 Download Chart {displayed + 1}",
                    data=image_bytes,
                    file_name=f"datascout_chart_{displayed + 1}.png",
                    mime="image/png",
                    key=f"download_chart_s3_{i}_{hash(uri)}"
                )
                displayed += 1
            except Exception as e:
                st.warning(f"⚠️ Could not load chart from S3: {str(e)}")

    if displayed == 0:
        st.info("No visualizations were generated.")
